import { readFile } from "node:fs/promises";

const html = await readFile("index.html", "utf8");
const js = await readFile("app.js", "utf8");
const css = await readFile("styles.css", "utf8");

const requiredIds = [
  "diagnosis-form",
  "customer-mode-btn",
  "expert-mode-btn",
  "customer-title",
  "customer-message",
  "customer-next-action",
  "customer-primary-action-btn",
  "customer-journey",
  "customer-journey-kicker",
  "customer-journey-title",
  "customer-journey-list",
  "confidence-value",
  "confidence-bar",
  "confidence-label",
  "confidence-decision-card",
  "confidence-tier-status",
  "confidence-tier-title",
  "confidence-tier-reason",
  "confidence-tier-next",
  "confidence-tier-list",
  "customer-photo-rescue-card",
  "customer-photo-rescue-kicker",
  "customer-photo-rescue-title",
  "customer-photo-rescue-message",
  "customer-photo-rescue-steps",
  "customer-photo-rescue-btn",
  "smart-diagnose-btn",
  "smartConcern",
  "quick-photo-btn",
  "sample-btn",
  "sample-basil-btn",
  "sample-rosemary-btn",
  "sample-strawberry-btn",
  "sample-pepper-btn",
  "growDevice",
  "device-hint",
  "device-profile-title",
  "device-profile-summary",
  "device-recommendation-title",
  "device-recommendation-summary",
  "device-fit-list",
  "device-plan-title",
  "device-plan-summary",
  "device-plan-grid",
  "device-plan-list",
  "apply-device-plan-btn",
  "auto-intake-card",
  "auto-intake-summary",
  "auto-intake-list",
  "edit-auto-intake-btn",
  "guided-photo-card",
  "guided-photo-title",
  "guided-photo-reason",
  "guided-photo-steps",
  "guided-photo-status",
  "guided-photo-upload-btn",
  "save-log-btn",
  "followupPhoto",
  "followup-loop-card",
  "followup-loop-title",
  "followup-loop-time",
  "followup-loop-photo",
  "followup-loop-success",
  "followup-loop-steps",
  "followup-loop-verdict",
  "followup-loop-upload-btn",
  "customer-reminder-card",
  "customer-reminder-kicker",
  "customer-reminder-title",
  "customer-reminder-message",
  "customer-reminder-meta",
  "customer-progress-card",
  "customer-progress-kicker",
  "customer-progress-title",
  "customer-progress-message",
  "customer-progress-meta",
  "reminder-strip",
  "reminder-schedule-list",
  "reset-tasks-btn",
  "matched-pathway-list",
  "minimal-question-list",
  "task-list",
  "copy-report-btn",
  "save-report-btn",
  "refresh-db-btn",
  "export-db-btn",
  "report-output",
  "copy-status",
  "db-status",
  "db-list",
  "db-search",
  "db-crop-filter",
  "db-medium-filter",
  "db-detail",
  "case-manager",
  "active-case-card",
  "case-status",
  "case-list",
  "case-timeline",
  "case-detail",
  "new-case-btn",
  "refresh-cases-btn",
  "notification-center",
  "notification-channel-panel",
  "notification-channel-in-app",
  "notification-channel-email",
  "notification-channel-sms",
  "notification-channel-wechat",
  "notification-email-target",
  "notification-sms-target",
  "notification-wechat-target",
  "save-notification-channels-btn",
  "sync-case-notifications-btn",
  "refresh-notifications-btn",
  "notification-status",
  "notification-metrics",
  "notification-list",
  "refresh-insights-btn",
  "insights-grid",
  "insights-list",
  "refresh-opportunities-btn",
  "opportunity-rank-list",
  "refresh-experiments-btn",
  "experiment-list",
  "refresh-product-strategy-btn",
  "product-strategy-grid",
  "product-strategy-list",
  "refresh-knowledge-graph-btn",
  "knowledge-graph-crop-filter",
  "knowledge-graph-stage-filter",
  "knowledge-graph-stats",
  "knowledge-graph-list",
  "followup-list",
  "history-list",
  "photo-list",
  "metrics-strip",
  "plantPhoto",
  "auto-photo-type-badge",
  "photoPreview",
  "reset-photo-check-btn",
  "next-photo-title",
  "next-photo-tip",
  "use-next-photo-btn",
  "photo-check-list",
  "photo-quality-list"
];

const missing = requiredIds.filter((id) => !html.includes(`id="${id}"`) || !js.includes(`#${id}`));

if (missing.length) {
  console.error(`Missing wired ids: ${missing.join(", ")}`);
  process.exit(1);
}

const requiredJsSnippets = [
  "function buildCustomerActions",
  "function pathwayCustomerAction",
  "async function loadProductStrategy",
  "function resizeImageForVision",
  "latestVisionResult",
  "latestPhotoTypeDetection",
  "vision: latestVisionResult",
  "photoTypeDetection: latestPhotoTypeDetection",
  "diagnosisRoute: route",
  "primaryRouteAction",
  "const deviceTemplates",
  "function applyDeviceTemplate",
  "function renderDeviceCropFit",
  "function deviceCropFitReason",
  "function buildDeviceCropPlan",
  "function renderDeviceCropPlan",
  "function autoFillCustomerIntake",
  "function renderAutoIntakeCard",
  "function detectUploadedPhotoType",
  "function applyPhotoTypeDetection",
  "function scorePhotoTypeKeywords",
  "function activeDiagnosisPhotoType",
  "function diagnosisRoute",
  "function applyDiagnosisRouteBoost",
  "function routeBoostsPathway",
  "function routePrimaryAction",
  "function guidedPhotoInstruction",
  "function renderGuidedPhotoCapture",
  "function openGuidedPhotoUpload",
  "function openSuggestedPhotoUpload",
  "function customerReminderSummary",
  "function renderCustomerReminderSummary",
  "function customerProgressSummary",
  "function renderCustomerProgressSummary",
  "function customerJourneyModel",
  "function renderCustomerJourney",
  "function customerTaskLabels",
  "function isWaitingForActionFollowup",
  "function currentCustomerTask",
  "function customerPrimaryActionModel",
  "function renderCustomerPrimaryAction",
  "function setTaskCompletion",
  "function rescheduleRemindersFromAction",
  "function followupItemsForCompletedAction",
  "function completedActionRouteKey",
  "function reminderItem",
  "function renderCustomerTaskFocus",
  "function refreshAfterCustomerAction",
  "function customerHasStarted",
  "plan?.items?.length",
  "动作已完成，等待复查",
  "处方已执行，等待复查验证",
  "function photoQualityProblems",
  "function customerPhotoRescuePlan",
  "function renderCustomerPhotoRescue",
  "function syncCustomerIntakeState",
  "function isReminderDue",
  "function saveFollowupLog",
  "function followupReportPayload",
  "async function syncFollowupCaseRecord",
  "autoSaved: options.auto === true",
  "eventType: \"followup\"",
  "followupPhoto.value = \"\"",
  "function diagnosisConfidenceDecision",
  "function renderConfidenceDecision",
  "function getActiveCase",
  "async function loadCases",
  "async function viewCase",
  "function renderCaseTimeline",
  "function latestCaseComparison",
  "function caseComparisonHtml",
  "function routeAssessmentHtml",
  "function trendClassName",
  "function trendReminderText",
  "function trendReminderHtml",
  "case-trend-card",
  "case-comparison-card",
  "case-route-assessment",
  "复查路径判断",
  "customer-journey-step",
  "当前状态",
  "customer-action",
  "customer-task-focus",
  "customer-action-queue",
  "customer-intake-empty",
  "customer-photo-rescue-needed",
  "自动识别为",
  "自动照片类型",
  "照片分流",
  "已进入${route.title}",
  "花果路径第一步",
  "根区路径第一步",
  "虫害路径第一步",
  "叶片路径第一步",
  "授粉或花果动作需要 3 天左右",
  "停水、降水位、遮光或通风动作通常先看 48 小时变化",
  "隔离和初步处理后 24 小时先看虫量方向",
  "成功标准",
  "照片看不准",
  "按提示重拍",
  "拍一张照片就能开始",
  "完成后再给下一步",
  "actionCompletedAt",
  "customer-followup-due",
  "has-plant-photo",
  "quickPhotoBtn.addEventListener",
  "现在拍复查照",
  "case-reminder-pill",
  "async function loadNotifications",
  "async function syncCaseNotifications",
  "async function simulateNotificationSend",
  "async function retryFailedNotification",
  "function getNotificationChannelConfig",
  "function channelStatusHtml",
  "function failureSuggestionHtml",
  "function notificationTemplateHtml",
  "notification-template-preview",
  "function followupLoopInstruction",
  "function renderFollowupLoop",
  "function followupAssessmentRouteKey",
  "function routeFollowupAssessment",
  "routeAssessment",
  "路径判断：",
  "坐果趋势在改善",
  "根区压力在下降",
  "虫害扩散被压住",
  "叶片状态在恢复",
  "followupLoopUploadBtn.addEventListener",
  "customerPrimaryActionBtn.addEventListener",
  "complete-current-task",
  "我已完成，安排复查",
  "等待复查",
  "当前动作已完成",
  "function openFollowupUpload",
  "function focusCustomerTarget",
  "guidedPhotoUploadBtn.addEventListener",
  "devicePlan: buildDeviceCropPlan",
  "首批种植方案",
  "设备/作物适配风险",
  "document.body.classList.contains(\"customer-mode\")",
  "findings.map((item) => item.action)"
];

const missingSnippets = requiredJsSnippets.filter((snippet) => !js.includes(snippet));

if (missingSnippets.length) {
  console.error(`Missing expected diagnosis UX logic: ${missingSnippets.join(", ")}`);
  process.exit(1);
}

const requiredCssSnippets = [
  "body.customer-mode .customer-detail",
  "body.customer-mode .confidence-decision-card",
  "body.customer-mode .customer-next",
  ".customer-primary-action",
  ".soft-focus",
  ".customer-journey-list",
  "body.customer-mode .confidence-meter",
  "body.customer-mode .result-grid",
  "body.customer-mode.customer-intake-empty .result-grid",
  "body.customer-mode.customer-intake-empty .followup-panel",
  "body.customer-mode #reset-tasks-btn",
  "body.customer-mode.customer-photo-rescue-needed .customer-photo-rescue-card",
  "body.customer-mode.customer-photo-rescue-needed .task-block",
  ".auto-photo-type-badge"
];

const missingCssSnippets = requiredCssSnippets.filter((snippet) => !css.includes(snippet));

if (missingCssSnippets.length) {
  console.error(`Missing expected customer-mode CSS: ${missingCssSnippets.join(", ")}`);
  process.exit(1);
}

console.log("smoke-test-ok");
