const query = new URLSearchParams(location.search);
const role = query.get("role") === "auditor" ? "auditor" : "client";
const principal = role === "auditor" ? "esg-auditor" : "client-show-suite";
const headers = { "x-dr-forest-principal": principal };
const $ = (selector) => document.querySelector(selector);
function escapeHtml(value) { return String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[char])); }
async function api(path) { const response = await fetch(path, { headers, credentials: "include" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`); return body; }
function renderSummary(portfolio) { const counts = portfolio.counts || {}; $("#asset-count").textContent = counts.assets ?? 0; $("#module-count").textContent = counts.modules ?? 0; $("#health-score").textContent = portfolio.health?.averageScore ?? "--"; $("#proof-count").textContent = counts.proofRecords ?? 0; $("#issue-count").textContent = (counts.openIncidents || 0) + (counts.activeSensorAlerts || 0); }
function renderAssets(items) { $("#asset-state").textContent = `${items.length} in scope`; $("#asset-list").innerHTML = items.length ? items.map((item) => { const state = item.status === "risk" ? "risk" : item.status === "watch" || item.sensorAlerts || item.openIncidents ? "warn" : ""; return `<div class="asset-row"><div><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.location || item.district || item.clientName)} · ${item.modules || 0} modules · ${item.openWorkorders || 0} open visits</span></div><span class="state ${state}">${escapeHtml(item.status || "active")}</span></div>`; }).join("") : "<p class=\"empty\">No scoped assets / 沒有範圍內資產</p>"; }
function renderEvidence(objects) { const verified = objects.filter((item) => ["registered", "verified"].includes(item.uploadStatus)); $("#proof-state").textContent = `${verified.length} verified`; $("#evidence-list").innerHTML = verified.length ? verified.slice(0, 8).map((item) => `<div class="evidence-row"><div><strong>${escapeHtml(item.filename)}</strong><span>${escapeHtml(item.category)} · ${escapeHtml(item.moduleId || item.wallId)} · ${escapeHtml(item.uploadStatus)}</span></div><span class="state">SHA-256</span></div>`).join("") : "<p class=\"empty\">No verified media yet / 暫無已驗證影像</p>"; }
function renderExceptions(alerts, diagnoses) { const rows = [...alerts.filter((item) => ["open", "acknowledged"].includes(item.status)).slice(0, 6).map((item) => ({ title: `${item.metric} · ${item.moduleId || item.wallId}`, detail: item.reason, state: item.status })), ...diagnoses.filter((item) => ["queued", "running"].includes(item.status)).slice(0, 4).map((item) => ({ title: `AI vision · ${item.moduleId}`, detail: `Capture ${item.captureId}`, state: item.status }))]; $("#exception-state").textContent = `${rows.length} active`; $("#exception-list").innerHTML = rows.length ? rows.map((item) => `<div class="exception-row"><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span></div><span class="state warn">${escapeHtml(item.state)}</span></div>`).join("") : "<p class=\"empty\">No active exceptions / 沒有未結例外</p>"; }
function renderQuality(quality) { const checks = quality.relationshipChecks || []; const passed = checks.reduce((total, item) => total + Number(item.passed || 0), 0); const total = checks.reduce((sum, item) => sum + Number(item.total || 0), 0); $("#quality-status").textContent = quality.status || "unknown"; $("#quality-coverage").textContent = `${passed}/${total}`; $("#quality-scale").textContent = quality.scaleReadiness?.currentModules ?? "--"; $("#quality-gaps").textContent = quality.warnings?.length ?? 0; $("#quality-list").innerHTML = (quality.warnings || []).slice(0, 8).map((item) => `<li>${escapeHtml(item)}</li>`).join("") || "<li>No warnings / 沒有警告</li>"; }
async function load() { $("#notice").textContent = ""; $("#portal-mode").textContent = role === "auditor" ? "ESG Auditor" : "Client Viewer"; $("#portal-title").textContent = role === "auditor" ? "Evidence quality review" : "Living asset evidence"; $("#role-switch").value = role; const requests = await Promise.all([api("/api/portfolio"), api("/api/assets"), api("/api/proof/media-vault"), api("/api/telemetry/alerts?statuses=open,acknowledged"), api("/api/ai/visual-diagnoses?statuses=queued,running"), role === "auditor" ? api("/api/data-quality") : Promise.resolve(null)]); const [portfolio, assets, proof, alerts, diagnoses, quality] = requests; renderSummary(portfolio); renderAssets(assets.assets || []); renderEvidence(proof.objects || []); renderExceptions(alerts.alerts || [], diagnoses.diagnoses || []); if (role === "auditor") { $("#auditor-panel").hidden = false; renderQuality(quality); } }
$("#refresh").onclick = () => load().catch((error) => { $("#notice").textContent = error.message; });
$("#role-switch").onchange = (event) => { location.href = `portal.html?role=${encodeURIComponent(event.target.value)}`; };
load().catch((error) => { $("#notice").textContent = error.message; });
